name: Daily Job Search 📬

on:
  schedule:
    - cron: '30 1 * * *'  # 7:00 AM IST daily (~1:30 AM UTC)
  workflow_dispatch:

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python job_search.py
      - env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python send_email.py
